import VideoPlayer from "@/components/video-player/VideoPlayer";
import DocsSection from "@/components/video-player/DocsSection";

export default function Page() {
  return (
    <div className="min-h-screen bg-background font-sans text-foreground">
      {/* Header */}
      <header className="border-b border-border sticky top-0 z-50 bg-background/80 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center flex-shrink-0">
              <svg
                className="w-4 h-4 text-primary-foreground"
                fill="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  fillRule="evenodd"
                  d="M4.5 5.653c0-1.427 1.529-2.33 2.779-1.643l11.54 6.347c1.295.712 1.295 2.573 0 3.286L7.28 19.99c-1.25.687-2.779-.217-2.779-1.643V5.653Z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <span className="font-bold text-foreground text-lg tracking-tight">
              CinePlay
            </span>
          </div>

          <nav className="hidden sm:flex items-center gap-6 text-sm text-muted-foreground">
            <a href="#player" className="hover:text-foreground transition-colors">
              Player
            </a>
            <a
              href="#usage"
              className="hover:text-foreground transition-colors"
            >
              Usage
            </a>
            <a
              href="#formats"
              className="hover:text-foreground transition-colors"
            >
              Formats
            </a>
            <a
              href="#architecture"
              className="hover:text-foreground transition-colors"
            >
              Architecture
            </a>
          </nav>

          <span className="text-xs text-muted-foreground bg-secondary px-3 py-1 rounded-full border border-border">
            100% Client-Side
          </span>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 pb-24">
        {/* Hero */}
        <section className="pt-12 pb-10 text-center">
          <div className="inline-flex items-center gap-2 bg-primary/10 border border-primary/30 text-primary text-xs font-semibold px-3 py-1.5 rounded-full mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-primary inline-block" />
            No server. No upload. Pure browser.
          </div>
          <h1 className="text-3xl sm:text-5xl font-bold text-foreground text-balance leading-tight">
            Browser Video Player
          </h1>
          <p className="mt-4 text-muted-foreground max-w-2xl mx-auto leading-relaxed text-balance">
            Play MP4, WebM, MOV, and MKV files directly in your browser with
            custom controls, keyboard shortcuts, and real-time format
            detection — no extensions, no server, complete privacy.
          </p>
        </section>

        {/* Player section */}
        <section id="player" className="scroll-mt-20">
          <VideoPlayer />
        </section>

        {/* Docs */}
        <DocsSection />
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-8 mt-8">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded bg-primary/20 flex items-center justify-center">
              <svg
                className="w-3 h-3 text-primary"
                fill="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  fillRule="evenodd"
                  d="M4.5 5.653c0-1.427 1.529-2.33 2.779-1.643l11.54 6.347c1.295.712 1.295 2.573 0 3.286L7.28 19.99c-1.25.687-2.779-.217-2.779-1.643V5.653Z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <span className="text-sm font-semibold text-foreground">
              CinePlay
            </span>
          </div>

          <div className="flex flex-col items-center gap-1">
            <p className="text-xs text-muted-foreground text-center">
              Files are processed entirely in your browser. Nothing is uploaded
              to any server.
            </p>
            <p className="text-xs text-muted-foreground/50">
              Generated by Superagent.
            </p>
          </div>

          <div className="flex gap-4 text-xs text-muted-foreground">
            <span>MP4 ✓</span>
            <span>WebM ✓</span>
            <span>MOV ~</span>
            <span>MKV ~</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
